//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class ActualizacionesPendientes
{
    public int ID { get; set; }
    public Nullable<int> PdaID { get; set; }
    public Nullable<int> CaracteristicaID { get; set; }

    public virtual Caracteristica Caracteristica { get; set; }
    public virtual Pda Pda { get; set; }
}

public partial class Aparato
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Aparato()
    {
        this.ItemCotizacion = new HashSet<ItemCotizacion>();
        this.ListaPrecio = new HashSet<ListaPrecio>();
        this.Inspeccion = new HashSet<Inspeccion>();
    }

    public int ID { get; set; }
    public string Nombre { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<ItemCotizacion> ItemCotizacion { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<ListaPrecio> ListaPrecio { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Inspeccion> Inspeccion { get; set; }
}

public partial class ArchivoCotizacion
{
    public int id { get; set; }
    public Nullable<int> idCotizacion { get; set; }
    public Nullable<int> idArchivo { get; set; }

    public virtual Archivos Archivos { get; set; }
    public virtual Cotizacion Cotizacion { get; set; }
}

public partial class Archivos
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Archivos()
    {
        this.ArchivoCotizacion = new HashSet<ArchivoCotizacion>();
    }

    public int Id { get; set; }
    public string URL { get; set; }
    public string Nombre { get; set; }
    public string Extension { get; set; }
    public string Uso { get; set; }
    public Nullable<bool> Habilitado { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<ArchivoCotizacion> ArchivoCotizacion { get; set; }
}

public partial class Caracteristica
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Caracteristica()
    {
        this.ActualizacionesPendientes = new HashSet<ActualizacionesPendientes>();
        this.Cumplimiento = new HashSet<Cumplimiento>();
    }

    public int ID { get; set; }
    public string Descripcion { get; set; }
    public Nullable<int> RequisitoID { get; set; }
    public bool Habilitado { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<ActualizacionesPendientes> ActualizacionesPendientes { get; set; }
    public virtual Requisito Requisito { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Cumplimiento> Cumplimiento { get; set; }
}

public partial class Ciudad
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Ciudad()
    {
        this.Cotizacion = new HashSet<Cotizacion>();
        this.ListaPrecioCostosLogisticos = new HashSet<ListaPrecioCostosLogisticos>();
    }

    public int Id { get; set; }
    public string Descripcion { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Cotizacion> Cotizacion { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<ListaPrecioCostosLogisticos> ListaPrecioCostosLogisticos { get; set; }
}

public partial class Cliente
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Cliente()
    {
        this.Cotizacion = new HashSet<Cotizacion>();
        this.Servicio = new HashSet<Servicio>();
    }

    public int ID { get; set; }
    public string Rut { get; set; }
    public string Nombre { get; set; }
    public string Direccion { get; set; }
    public string TelefonoContacto { get; set; }
    public string EmailContacto { get; set; }
    public bool Habilitado { get; set; }
    public string Giro { get; set; }
    public Nullable<int> DescuentoPorc { get; set; }
    public string NombreContacto { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Cotizacion> Cotizacion { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Servicio> Servicio { get; set; }
}

public partial class Cotizacion
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Cotizacion()
    {
        this.ArchivoCotizacion = new HashSet<ArchivoCotizacion>();
        this.GastoOperacional = new HashSet<GastoOperacional>();
        this.Hito = new HashSet<Hito>();
        this.DescuentosRecargos = new HashSet<DescuentosRecargos>();
        this.ItemCotizacion = new HashSet<ItemCotizacion>();
        this.Servicio = new HashSet<Servicio>();
    }

    public int Id { get; set; }
    public Nullable<int> ClienteId { get; set; }
    public Nullable<System.DateTime> FechaDoc { get; set; }
    public Nullable<System.DateTime> FechaSolicitud { get; set; }
    public string FuenteSolicitud { get; set; }
    public Nullable<int> FormaDePagoId { get; set; }
    public Nullable<int> MonedaId { get; set; }
    public Nullable<int> EstadoId { get; set; }
    public string Vendedor { get; set; }
    public string Observacion { get; set; }
    public Nullable<double> Valor { get; set; }
    public Nullable<double> Descuento { get; set; }
    public Nullable<double> Recargo { get; set; }
    public Nullable<double> Total { get; set; }
    public string Usuario { get; set; }
    public Nullable<System.DateTime> FechaCreacion { get; set; }
    public Nullable<int> IT { get; set; }
    public string Filename { get; set; }
    public string Nota { get; set; }
    public Nullable<int> CiudadId { get; set; }
    public Nullable<System.DateTime> FechaValidez { get; set; }
    public Nullable<bool> CreadaFase2 { get; set; }
    public Nullable<System.DateTime> FechaCompromisoFase2 { get; set; }
    public Nullable<bool> AlertaFase2Enviada { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<ArchivoCotizacion> ArchivoCotizacion { get; set; }
    public virtual Ciudad Ciudad { get; set; }
    public virtual Cliente Cliente { get; set; }
    public virtual Usuario Usuario1 { get; set; }
    public virtual Usuario Usuario2 { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<GastoOperacional> GastoOperacional { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Hito> Hito { get; set; }
    public virtual EstadoCotizacion EstadoCotizacion { get; set; }
    public virtual FormaDePago FormaDePago { get; set; }
    public virtual Moneda Moneda { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<DescuentosRecargos> DescuentosRecargos { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<ItemCotizacion> ItemCotizacion { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Servicio> Servicio { get; set; }
}

public partial class Cumplimiento
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Cumplimiento()
    {
        this.Fotografias = new HashSet<Fotografias>();
    }

    public int ID { get; set; }
    public Nullable<int> InspeccionID { get; set; }
    public Nullable<int> CaracteristicaID { get; set; }
    public Nullable<int> EvaluacionID { get; set; }
    public string Observacion { get; set; }
    public string Fotografia { get; set; }
    public Nullable<System.DateTime> Fecha { get; set; }

    public virtual Caracteristica Caracteristica { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Fotografias> Fotografias { get; set; }
    public virtual Evaluacion Evaluacion { get; set; }
    public virtual Inspeccion Inspeccion { get; set; }
}

public partial class CustomInforme
{
    public int ID { get; set; }
    public Nullable<int> EstructuraID { get; set; }
    public Nullable<int> InspeccionID { get; set; }
    public string Texto { get; set; }

    public virtual EstructuraInfome EstructuraInfome { get; set; }
    public virtual Inspeccion Inspeccion { get; set; }
}

public partial class DescuentosRecargos
{
    public int Id { get; set; }
    public Nullable<int> CotizacionId { get; set; }
    public Nullable<int> TipoOperacion { get; set; }
    public Nullable<int> TipoValor { get; set; }
    public Nullable<int> Valor { get; set; }
    public Nullable<bool> Exento { get; set; }
    public string Glosa { get; set; }

    public virtual Cotizacion Cotizacion { get; set; }
}

public partial class DescuentosYRecargos
{
    public int Id { get; set; }
    public string TipoOperacion { get; set; }
    public string TipoValor { get; set; }
    public Nullable<int> Valor { get; set; }
    public string Glosa { get; set; }
    public Nullable<int> CotizacionId { get; set; }
}

public partial class DestinoProyecto
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public DestinoProyecto()
    {
        this.Inspeccion = new HashSet<Inspeccion>();
    }

    public int ID { get; set; }
    public string Descripcion { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Inspeccion> Inspeccion { get; set; }
}

public partial class EquipoUtilizado
{
    public int ID { get; set; }
    public string Tipo { get; set; }
    public string Identificacion { get; set; }
    public string Usuario { get; set; }
    public string Ident { get; set; }

    public virtual Usuario Usuario1 { get; set; }
}

public partial class Especificos
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Especificos()
    {
        this.ValoresEspecificos = new HashSet<ValoresEspecificos>();
    }

    public int ID { get; set; }
    public string Nombre { get; set; }
    public Nullable<int> NroTable { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<ValoresEspecificos> ValoresEspecificos { get; set; }
}

public partial class EstadoCotizacion
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public EstadoCotizacion()
    {
        this.Cotizacion = new HashSet<Cotizacion>();
        this.TipoHito = new HashSet<TipoHito>();
    }

    public int Id { get; set; }
    public string Descripcion { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Cotizacion> Cotizacion { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<TipoHito> TipoHito { get; set; }
}

public partial class EstadoInspeccion
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public EstadoInspeccion()
    {
        this.Inspeccion = new HashSet<Inspeccion>();
    }

    public int ID { get; set; }
    public string Descripcion { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Inspeccion> Inspeccion { get; set; }
}

public partial class EstadoServicio
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public EstadoServicio()
    {
        this.Servicio = new HashSet<Servicio>();
    }

    public int ID { get; set; }
    public string Descripcion { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Servicio> Servicio { get; set; }
}

public partial class EstructuraInfome
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public EstructuraInfome()
    {
        this.CustomInforme = new HashSet<CustomInforme>();
    }

    public int ID { get; set; }
    public string Nombre { get; set; }
    public Nullable<int> Orden { get; set; }
    public string Título { get; set; }
    public string Texto { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<CustomInforme> CustomInforme { get; set; }
}

public partial class Evaluacion
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Evaluacion()
    {
        this.Cumplimiento = new HashSet<Cumplimiento>();
    }

    public int ID { get; set; }
    public string Glosa { get; set; }
    public string Descripcion { get; set; }
    public Nullable<int> Fase { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Cumplimiento> Cumplimiento { get; set; }
}

public partial class FormaDePago
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public FormaDePago()
    {
        this.Cotizacion = new HashSet<Cotizacion>();
    }

    public int Id { get; set; }
    public string Descripcion { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Cotizacion> Cotizacion { get; set; }
}

public partial class FormatoNorma
{
    public int ID { get; set; }
    public string Nombre { get; set; }
}

public partial class Fotografias
{
    public int ID { get; set; }
    public string URL { get; set; }
    public Nullable<int> CumplimientoID { get; set; }

    public virtual Cumplimiento Cumplimiento { get; set; }
}

public partial class FotografiaTecnica
{
    public int ID { get; set; }
    public string URL { get; set; }
    public Nullable<int> ObservacionTecnicaID { get; set; }

    public virtual ObservacionTecnica ObservacionTecnica { get; set; }
}

public partial class GastoOperacional
{
    public int Id { get; set; }
    public Nullable<int> TipoGastoId { get; set; }
    public Nullable<int> CotizacionId { get; set; }
    public Nullable<double> Valor { get; set; }
    public Nullable<int> Cantidad { get; set; }

    public virtual Cotizacion Cotizacion { get; set; }
    public virtual TipoGasto TipoGasto { get; set; }
}

public partial class Hito
{
    public int Id { get; set; }
    public Nullable<System.DateTime> Fecha { get; set; }
    public Nullable<int> TipoHitoId { get; set; }
    public string Observacion { get; set; }
    public Nullable<System.DateTime> FechaCompromiso { get; set; }
    public Nullable<int> CotizacionId { get; set; }

    public virtual Cotizacion Cotizacion { get; set; }
    public virtual TipoHito TipoHito { get; set; }
}

public partial class Informe
{
    public int ID { get; set; }
    public Nullable<System.DateTime> FechaElaboracion { get; set; }
    public Nullable<int> EstadoID { get; set; }
    public string FileName { get; set; }
    public Nullable<int> InspeccionID { get; set; }

    public virtual Inspeccion Inspeccion { get; set; }
}

public partial class Inspeccion
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Inspeccion()
    {
        this.Cumplimiento = new HashSet<Cumplimiento>();
        this.CustomInforme = new HashSet<CustomInforme>();
        this.Informe = new HashSet<Informe>();
        this.Inspeccion1 = new HashSet<Inspeccion>();
        this.InspeccionNorma = new HashSet<InspeccionNorma>();
        this.ObservacionTecnica = new HashSet<ObservacionTecnica>();
        this.ValoresEspecificos = new HashSet<ValoresEspecificos>();
    }

    public int ID { get; set; }
    public string IT { get; set; }
    public Nullable<int> AparatoID { get; set; }
    public Nullable<int> TipoFuncionamientoID { get; set; }
    public int EstadoID { get; set; }
    public int ServicioID { get; set; }
    public string Ingeniero { get; set; }
    public System.DateTime FechaCreacion { get; set; }
    public Nullable<System.DateTime> FechaInspeccion { get; set; }
    public string Ubicacion { get; set; }
    public Nullable<System.DateTime> FechaInstalacion { get; set; }
    public string Destinatario { get; set; }
    public string PermisoEdificacion { get; set; }
    public string RecepcionMunicipal { get; set; }
    public Nullable<int> AlturaPisos { get; set; }
    public int Fase { get; set; }
    public string Numero { get; set; }
    public Nullable<System.DateTime> FechaRevision { get; set; }
    public Nullable<System.DateTime> FechaAprobacion { get; set; }
    public Nullable<System.DateTime> FechaEntrega { get; set; }
    public string NombreProyecto { get; set; }
    public string NombreEdificio { get; set; }
    public string Revisador { get; set; }
    public string Aprobador { get; set; }
    public Nullable<int> Calificacion { get; set; }
    public Nullable<int> DiasPlazo { get; set; }
    public Nullable<int> TipoInformeID { get; set; }
    public Nullable<int> InspeccionFase1 { get; set; }
    public Nullable<int> DestinoProyectoID { get; set; }
    public Nullable<bool> CreaFaseSiguiente { get; set; }
    public Nullable<System.DateTime> FechaEmisionCertificado { get; set; }
    public Nullable<System.DateTime> FechaVencimientoCertificado { get; set; }

    public virtual Aparato Aparato { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Cumplimiento> Cumplimiento { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<CustomInforme> CustomInforme { get; set; }
    public virtual DestinoProyecto DestinoProyecto { get; set; }
    public virtual EstadoInspeccion EstadoInspeccion { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Informe> Informe { get; set; }
    public virtual Usuario Usuario { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Inspeccion> Inspeccion1 { get; set; }
    public virtual Inspeccion Inspeccion2 { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<InspeccionNorma> InspeccionNorma { get; set; }
    public virtual Usuario Usuario1 { get; set; }
    public virtual TipoInforme TipoInforme { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<ObservacionTecnica> ObservacionTecnica { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<ValoresEspecificos> ValoresEspecificos { get; set; }
    public virtual Servicio Servicio { get; set; }
    public virtual TipoFuncionamientoAparato TipoFuncionamientoAparato { get; set; }
    public virtual Usuario Usuario2 { get; set; }
}

public partial class InspeccionNorma
{
    public int ID { get; set; }
    public Nullable<int> InspeccionID { get; set; }
    public Nullable<int> NormaID { get; set; }

    public virtual Inspeccion Inspeccion { get; set; }
    public virtual Norma Norma { get; set; }
}

public partial class ItemCotizacion
{
    public int Id { get; set; }
    public Nullable<int> ProductoId { get; set; }
    public string DescripcionEditada { get; set; }
    public Nullable<int> Cantidad { get; set; }
    public Nullable<double> Unitario { get; set; }
    public Nullable<double> Descuento { get; set; }
    public string ModoDescuento { get; set; }
    public Nullable<int> CotizacionId { get; set; }
    public Nullable<bool> Exento { get; set; }
    public Nullable<int> AparatoID { get; set; }
    public Nullable<int> TipoFuncionamientoID { get; set; }
    public Nullable<int> AlturaPisos { get; set; }
    public string Uso { get; set; }
    public Nullable<int> MarcaID { get; set; }
    public Nullable<int> InstalacionAno { get; set; }
    public string EmpresaInstaladora { get; set; }
    public string Ubicacion { get; set; }
    public Nullable<double> ValorDescuento { get; set; }

    public virtual Aparato Aparato { get; set; }
    public virtual Cotizacion Cotizacion { get; set; }
    public virtual Marca Marca { get; set; }
    public virtual TipoFuncionamientoAparato TipoFuncionamientoAparato { get; set; }
    public virtual Producto Producto { get; set; }
}

public partial class ListaPrecio
{
    public int Id { get; set; }
    public Nullable<int> TipoElevadorId { get; set; }
    public Nullable<int> Paradas { get; set; }
    public Nullable<bool> MasDe1Equipo { get; set; }
    public Nullable<int> ProductoId { get; set; }
    public Nullable<double> ValorUF { get; set; }

    public virtual Aparato Aparato { get; set; }
    public virtual Producto Producto { get; set; }
}

public partial class ListaPrecioCostosLogisticos
{
    public int Id { get; set; }
    public Nullable<int> CiudadId { get; set; }
    public Nullable<int> TipoGastoId { get; set; }
    public Nullable<double> ValorCLP { get; set; }

    public virtual Ciudad Ciudad { get; set; }
    public virtual TipoGasto TipoGasto { get; set; }
}

public partial class Marca
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Marca()
    {
        this.ItemCotizacion = new HashSet<ItemCotizacion>();
    }

    public int Id { get; set; }
    public string Descripcion { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<ItemCotizacion> ItemCotizacion { get; set; }
}

public partial class MenuAcceso
{
    public int ID { get; set; }
    public Nullable<int> MenuModuloID { get; set; }
    public Nullable<int> RolID { get; set; }

    public virtual MenuModulo MenuModulo { get; set; }
    public virtual Rol Rol { get; set; }
}

public partial class MenuModulo
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public MenuModulo()
    {
        this.MenuAcceso = new HashSet<MenuAcceso>();
        this.MenuModulo1 = new HashSet<MenuModulo>();
    }

    public int ID { get; set; }
    public string Nombre { get; set; }
    public string Descripcion { get; set; }
    public string URL { get; set; }
    public string FontAwesomeIcon { get; set; }
    public Nullable<int> MenuModulosID { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<MenuAcceso> MenuAcceso { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<MenuModulo> MenuModulo1 { get; set; }
    public virtual MenuModulo MenuModulo2 { get; set; }
}

public partial class Moneda
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Moneda()
    {
        this.Cotizacion = new HashSet<Cotizacion>();
        this.Producto = new HashSet<Producto>();
    }

    public int Id { get; set; }
    public string Descripcion { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Cotizacion> Cotizacion { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Producto> Producto { get; set; }
}

public partial class Norma
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Norma()
    {
        this.InspeccionNorma = new HashSet<InspeccionNorma>();
        this.NormasAsociadas = new HashSet<NormasAsociadas>();
        this.NormasAsociadas1 = new HashSet<NormasAsociadas>();
        this.TerminosYDefiniciones = new HashSet<TerminosYDefiniciones>();
        this.Titulo = new HashSet<Titulo>();
    }

    public int ID { get; set; }
    public string Nombre { get; set; }
    public Nullable<int> TipoNormaID { get; set; }
    public string TituloRegulacion { get; set; }
    public Nullable<bool> Habilitado { get; set; }
    public string ParrafoIntroductorio { get; set; }
    public Nullable<int> TipoInformeID { get; set; }
    public Nullable<bool> Principal { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<InspeccionNorma> InspeccionNorma { get; set; }
    public virtual TipoInforme TipoInforme { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<NormasAsociadas> NormasAsociadas { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<NormasAsociadas> NormasAsociadas1 { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<TerminosYDefiniciones> TerminosYDefiniciones { get; set; }
    public virtual TipoNorma TipoNorma { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Titulo> Titulo { get; set; }
}

public partial class NormasAsociadas
{
    public int ID { get; set; }
    public Nullable<int> NormaPrincipalID { get; set; }
    public Nullable<int> NormaSecundariaID { get; set; }

    public virtual Norma Norma { get; set; }
    public virtual Norma Norma1 { get; set; }
}

public partial class ObservacionTecnica
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public ObservacionTecnica()
    {
        this.FotografiaTecnica = new HashSet<FotografiaTecnica>();
    }

    public int ID { get; set; }
    public string Texto { get; set; }
    public Nullable<int> InspeccionID { get; set; }
    public Nullable<bool> CorregidoEnFase2 { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<FotografiaTecnica> FotografiaTecnica { get; set; }
    public virtual Inspeccion Inspeccion { get; set; }
}

public partial class Pda
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Pda()
    {
        this.ActualizacionesPendientes = new HashSet<ActualizacionesPendientes>();
    }

    public int ID { get; set; }
    public string ESN { get; set; }
    public string Usuario { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<ActualizacionesPendientes> ActualizacionesPendientes { get; set; }
    public virtual Usuario Usuario1 { get; set; }
}

public partial class Producto
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Producto()
    {
        this.ItemCotizacion = new HashSet<ItemCotizacion>();
        this.ListaPrecio = new HashSet<ListaPrecio>();
    }

    public int Id { get; set; }
    public string Codigo { get; set; }
    public string Descripcion { get; set; }
    public Nullable<int> PrecioReferencia { get; set; }
    public Nullable<int> MonedaId { get; set; }
    public Nullable<bool> Habilitado { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<ItemCotizacion> ItemCotizacion { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<ListaPrecio> ListaPrecio { get; set; }
    public virtual Moneda Moneda { get; set; }
}

public partial class Requisito
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Requisito()
    {
        this.Caracteristica = new HashSet<Caracteristica>();
    }

    public int ID { get; set; }
    public string Descripcion { get; set; }
    public Nullable<int> TituloID { get; set; }
    public Nullable<bool> Habilitado { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Caracteristica> Caracteristica { get; set; }
    public virtual Titulo Titulo { get; set; }
}

public partial class Rol
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Rol()
    {
        this.MenuAcceso = new HashSet<MenuAcceso>();
        this.UsuarioRol = new HashSet<UsuarioRol>();
    }

    public int ID { get; set; }
    public string Nombre { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<MenuAcceso> MenuAcceso { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<UsuarioRol> UsuarioRol { get; set; }
}

public partial class Servicio
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Servicio()
    {
        this.Inspeccion = new HashSet<Inspeccion>();
    }

    public int ID { get; set; }
    public System.DateTime FechaCreacion { get; set; }
    public int ClienteID { get; set; }
    public string IT { get; set; }
    public Nullable<int> EstadoID { get; set; }
    public Nullable<int> CotizacionID { get; set; }
    public Nullable<System.DateTime> fechaCompromiso { get; set; }

    public virtual Cliente Cliente { get; set; }
    public virtual EstadoServicio EstadoServicio { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Inspeccion> Inspeccion { get; set; }
    public virtual Cotizacion Cotizacion { get; set; }
}

public partial class Settings
{
    public string Clave { get; set; }
    public string Valor { get; set; }
    public Nullable<System.DateTime> Fecha { get; set; }
}

public partial class TerminosYDefiniciones
{
    public int ID { get; set; }
    public string Termino { get; set; }
    public string Definicion { get; set; }
    public Nullable<int> NormaID { get; set; }

    public virtual Norma Norma { get; set; }
}

public partial class TipoFuncionamientoAparato
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public TipoFuncionamientoAparato()
    {
        this.Inspeccion = new HashSet<Inspeccion>();
        this.ItemCotizacion = new HashSet<ItemCotizacion>();
    }

    public int ID { get; set; }
    public string Descripcion { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Inspeccion> Inspeccion { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<ItemCotizacion> ItemCotizacion { get; set; }
}

public partial class TipoGasto
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public TipoGasto()
    {
        this.GastoOperacional = new HashSet<GastoOperacional>();
        this.ListaPrecioCostosLogisticos = new HashSet<ListaPrecioCostosLogisticos>();
    }

    public int Id { get; set; }
    public string Descripcion { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<GastoOperacional> GastoOperacional { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<ListaPrecioCostosLogisticos> ListaPrecioCostosLogisticos { get; set; }
}

public partial class TipoHito
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public TipoHito()
    {
        this.Hito = new HashSet<Hito>();
    }

    public int Id { get; set; }
    public string Descripcion { get; set; }
    public Nullable<int> EstadoCotizacionId { get; set; }
    public Nullable<bool> FechaCompromiso { get; set; }

    public virtual EstadoCotizacion EstadoCotizacion { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Hito> Hito { get; set; }
}

public partial class TipoInforme
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public TipoInforme()
    {
        this.Inspeccion = new HashSet<Inspeccion>();
        this.Norma = new HashSet<Norma>();
    }

    public int ID { get; set; }
    public string Descripcion { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Inspeccion> Inspeccion { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Norma> Norma { get; set; }
}

public partial class TipoNorma
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public TipoNorma()
    {
        this.Norma = new HashSet<Norma>();
    }

    public int ID { get; set; }
    public string Descripcion { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Norma> Norma { get; set; }
}

public partial class Titulo
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Titulo()
    {
        this.Requisito = new HashSet<Requisito>();
    }

    public int ID { get; set; }
    public string Texto { get; set; }
    public Nullable<int> NormaID { get; set; }

    public virtual Norma Norma { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Requisito> Requisito { get; set; }
}

public partial class Usuario
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Usuario()
    {
        this.Cotizacion = new HashSet<Cotizacion>();
        this.Cotizacion1 = new HashSet<Cotizacion>();
        this.EquipoUtilizado = new HashSet<EquipoUtilizado>();
        this.Inspeccion = new HashSet<Inspeccion>();
        this.Inspeccion1 = new HashSet<Inspeccion>();
        this.Inspeccion2 = new HashSet<Inspeccion>();
        this.Pda = new HashSet<Pda>();
        this.UsuarioRol = new HashSet<UsuarioRol>();
    }

    public string NombreUsuario { get; set; }
    public string Nombre { get; set; }
    public string Apellido { get; set; }
    public string Pass { get; set; }
    public Nullable<int> EstadoID { get; set; }
    public Nullable<bool> Habilitado { get; set; }
    public string Cargo { get; set; }
    public Nullable<int> NumeroUnico { get; set; }
    public string Email { get; set; }
    public string Firma { get; set; }
    public string PassMail { get; set; }
    public string Fono { get; set; }
    public string Celular { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Cotizacion> Cotizacion { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Cotizacion> Cotizacion1 { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<EquipoUtilizado> EquipoUtilizado { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Inspeccion> Inspeccion { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Inspeccion> Inspeccion1 { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Inspeccion> Inspeccion2 { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Pda> Pda { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<UsuarioRol> UsuarioRol { get; set; }
}

public partial class UsuarioRol
{
    public int ID { get; set; }
    public string Usuario { get; set; }
    public Nullable<int> Rol { get; set; }

    public virtual Rol Rol1 { get; set; }
    public virtual Usuario Usuario1 { get; set; }
}

public partial class ValoresEspecificos
{
    public int ID { get; set; }
    public Nullable<int> EspecificoID { get; set; }
    public Nullable<int> InspeccionID { get; set; }
    public string Valor { get; set; }

    public virtual Especificos Especificos { get; set; }
    public virtual Inspeccion Inspeccion { get; set; }
}
